version: '3.3'

services:
  php:
      build:
        context: .
        dockerfile: dockerfile
      container_name: php8BB
      depends_on:
      - db
      image: php:8.0-apache
      volumes:
      - ./php:/var/www/html/
      ports:
      - 80:80
  db:
      container_name: mysql8BB
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment: 
        MYSQL_ROOT_PASSWORD: sdfjqgsfhg987
        MYSQL_DATABASE: BlagBlog
        MYSQL_USER: killard
        MYSQL_PASSWORD: killard95
      ports:
      - 3306:3306
  phpmya:
      image: phpmyadmin/phpmyadmin:latest
      container_name: pmaBB2023
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_USER: killard
        PMA_PASSWORD: killard95
        UPLOAD_LIMIT: 320M
      ports:
      - 8899:80